galaxy_info:
  author: SEINEP / SEGSAP - Helder
  description: my description
  company: TRF2
  license: GPL-3.0-only
  min_ansible_version: 2.4
  platforms:
  - name: EL
    versions:
    - 7
    - 8
  galaxy_tags: []

dependencies: 
  - rl_systemd
  