---
# tasks file for rl_firewalld

- name: Execute systemd action
  include_tasks:
    file: firewall-action.yml
  loop: "{{ firewalld_conf }}"
  loop_control:
    loop_var: firewalld_item
  tags:
    - firewalld_config

