---
driver:
  name: docker

provisioner:
  name: chef_solo
  product_name: chef
  product_version: 14.12.3

platforms:
  - name: centos
    driver_config:
      image: centos/systemd
      socket: npipe:////./pipe/docker_engine
      use_sudo: false
      privileged: true
      volume: /sys/fs/cgroup:/sys/fs/cgroup:ro

suites:
  - name: default
    network:
      - "public_network"
    run_list:
      - recipe[jboss-eap::default]
